export const tasks = [
   {
      id: '1',
      heading: 'Написать фронт',
      description: 'Какое-то описание',
      director: 'Федоров Алексей Юрьевич',
      responsible: 'Иванова Анна Сергеевна',
      priority: 'Срочно',
      status: 'Выполнен',
      dateCreation: '12.04.2023',
      dateUpdate: '14.04.2023',
      deadline: '14.04.2023',
   },
   {
      id: '2',
      heading: 'Написать фронт',
      description: 'Какое-то описание',
      director: 'Павлова Маргарита Александровна',
      responsible: 'Киров Андрей Игоревич',
      priority: 'Срочно',
      status: 'Выполнен',
      dateCreation: '23.03.2023',
      dateUpdate: '27.03.2023',
      deadline: '15.04.2023',
   },
   {
      id: '3',
      heading: 'Написать фронт',
      description: 'Какое-то описание',
      director: 'Бродский Олег Владимирович',
      responsible: 'Корина Ирина Дмитриевна',
      priority: 'Срочно',
      status: 'В процессе',
      dateCreation: '11.04.2023',
      dateUpdate: '10.04.2023',
      deadline: '16.04.2023',
   },
   {
      id: '4',
      heading: 'Написать фронт',
      description: 'Какое-то описание',
      director: 'Бродский Олег Владимирович',
      responsible: 'Корина Ирина Дмитриевна',
      priority: 'Срочно',
      status: 'В процессе',
      dateCreation: '11.04.2023',
      dateUpdate: '10.04.2023',
      deadline: '17.04.2023',
   },
   {
      id: '5',
      heading: 'Написать фронт',
      description: 'Какое-то описание',
      director: 'Павлова Маргарита Александровна',
      responsible: 'Киров Андрей Игоревич',
      priority: 'Срочно',
      status: 'Выполнен',
      dateCreation: '23.03.2023',
      dateUpdate: '27.03.2023',
      deadline: '15.04.2023',
   },
   {
      id: '6',
      heading: 'Написать фронт',
      description: 'Какое-то описание',
      director: 'Бродский Олег Владимирович',
      responsible: 'Корина Ирина Дмитриевна',
      priority: 'Срочно',
      status: 'В процессе',
      dateCreation: '11.04.2023',
      dateUpdate: '10.04.2023',
      deadline: '14.04.2023',
   },
   {
      id: '7',
      heading: 'Написать фронт',
      description: 'Какое-то описание',
      director: 'Бродский Олег Владимирович',
      responsible: 'Корина Ирина Дмитриевна',
      priority: 'Срочно',
      status: 'В процессе',
      dateCreation: '11.04.2023',
      dateUpdate: '10.04.2023',
      deadline: '15.04.2023',
   },
]
